# Generated by Django 3.2.4 on 2021-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=64, null=True)),
                ('contagios', models.IntegerField(default=0)),
                ('vacunados', models.IntegerField(default=0)),
            ],
        ),
    ]
