# Generated by Django 3.2.4 on 2021-07-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='contagios',
        ),
        migrations.RemoveField(
            model_name='info',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='info',
            name='vacunados',
        ),
        migrations.AddField(
            model_name='info',
            name='casosActivos',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='casosCriticos',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='casosNuevos',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='casosRecuperados',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='casosTotales',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='pais',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
